import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientProviders } from "./client-providers";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    chain: string;
  };
}

export default function RootLayout({ children, params }: RootLayoutProps) {
  return (
    <html lang="en" className={cn(
      geistSans.variable,
      geistMono.variable,
      "antialiased"
    )}>
      <body>
        <ClientProviders initialBlockchainRid={params.chain}>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
